title: Axe Drax
tagline: The collective that oppose the company Drax.
description: >-
  The collective that oppose the company Drax. We are direct action
  groups, local campaigns and individuals.
url: "https://axedrax.uk"


permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-airtable-import



action_network:
  event_campaign: 8e44ce3c-551b-4d14-9192-3a39f9cde323

airtable:
  actions:
    app: app47RLfKgIKcYIKZ
    table: tblWptbdmJRRPeDjQ
    view: viwxHgIkpQizm0Pjg
    collection:
      layout: page
  social_media:
    app: app47RLfKgIKcYIKZ
    table: tblJ2UJA30ykzoKLW
    view: viwkpMX7eeVPrUzdS
  events:
    app: appeyYdXaVR7N3IkP
    table: tblEN3r6eYjhkiLUj
    view: viwwM3kKP90feRNc8
    collection:
      layout: page

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/photos/andomeniconi/NZ6_1708.jpg_1200.jpg

collections:
  events:
    output: true
  templates:
    output: false
  actions:
    output: true

future: true

facebook:
  publisher: https://www.facebook.com/axedraxlovetrees

logo: /assets/images/logo_new_small.png

source: .
destination: ./docs

exclude:
  - vendor

social:
  name: Axe Drax
  links:
    - https://www.facebook.com/axedraxgroup
    - https://www.instagram.com/axe_drax/
locale: en_GB
image: /assets/images/photos/andomeniconi/NZ6_1708.jpg_2400.jpg
