title: Axe Drax
tagline: The collective that oppose the company Drax.
description: >-
  The collective that oppose the company Drax. We are direct action
  groups, local campaigns and individuals.
url: "https://www.axedrax.uk"


permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap



action_network:
  event_campaign: 8e44ce3c-551b-4d14-9192-3a39f9cde323

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/photos/etd_drax.jpg

collections:
  events:
    output: true
  templates:
    output: false

future: true

facebook:
  publisher: https://www.facebook.com/axedraxlovetrees

logo: /assets/images/axedraxlogo_notext_circle.svg

source: .
destination: ./docs

exclude:
  - vendor

social:
  name: Axe Drax
  links:
    - https://www.facebook.com/axedraxlovetrees
    - https://www.instagram.com/axe_drax/
locale: en_GB
image: /assets/images/photos/etd_drax.jpg
